export const tempProjectId = `proj-zNbxS_nP`;
export const tempBrief = `Company: Solinn
Sector: Protection de l'enfance
Project: Company: Solinn
Sector: Aide sociale à l'enfance
Project: Cette application doit permettre au départements français qui sont en charge de l'aide social à l'enfance de pouvoir suivre en temps réel les places disponibles, Sécuriser la RGPD sur les dossiers de l'enfants. Pouvoir suivre les évolutions scolaires, professionnelles de l'enfant dans les lieu de placement. Enregistrer des documents de suivi. Les établissements doivent pouvoir saisir des rapports pour que le conseillé du département en charge de l'enfant puisse voir ce qu'il se passe. Cette plateforme web doit être sécurisé avec une logic de tous les droits sont fermés par défault et on les ouvres au fur et à mesure par des gestions de rôles/Groupes. La plateforme doit pouvoir faciliter la communication entre les professionnels internes et externes autour de l'enfant. Nous devons aussi pouvoir générer des documents, uploader, downloader et pour des questions de traçabilité RGPD, nous devons maintenir un historique anymisable de l'ensembles des modifications, création archivache etc de toutes les collections.
Je vais d'abord effectuer des recherches approfondies sur votre secteur avant de vous poser les premières questions.

[Solinn — Contexte et organisation]
Combien de départements utilisateurs visez-vous au lancement ?: 1 département pilote
Quels types de structures d'accueil seront connectés à la plateforme ?: MECS (Maison d'Enfants à Caractère Social), Familles d'accueil, Foyers de l'enfance, Lieux de vie et d'accueil (LVA), Services d'accueil de jour, Autres établissements médico-sociaux
Quels outils utilisez-vous aujourd'hui pour gérer les dossiers enfants et les places disponibles ? (logiciels, tableurs, papier…): Excel
Quel est le volume approximatif d'enfants suivis par département ?: 500 à 1 500
Quels professionnels externes au département doivent accéder à la plateforme ?: Éducateurs des établissements, Assistants familiaux, Psychologues / thérapeutes, Enseignants / établissements scolaires, Magistrats / juges des enfants, Médecins / professionnels de santé
La plateforme est-elle destinée uniquement à la France métropolitaine, ou aussi aux DOM-TOM ?: Métropole + DOM-TOM


[Le problème et la vision cible] Aujourd'hui, quel est le problème le plus concret que vous rencontrez dans le suivi des places et des enfants ? (ce qui vous coûte le plus de temps ou génère le plus d'erreurs): Le principale pb est que nous passons trop de temps à chercher des places dispo. Nous devons appeler à chaque fois tous les lieux potentiels. Normalement les établissements devraient nous faire remonter leurs places dispo mais ils ne le font pas ou presque pas. ET nous ne sommes pas en règles RGPD Les dossiers des enfants contiendront-ils des informations médicales ou de santé (traitements, handicap, suivi psy) ?: Oui, des informations médicales seront présentes Avez-vous des données existantes (fichiers Excel, documents) à intégrer dans la nouvelle plateforme au démarrage ?: Partiellement, certaines données seulement La plateforme devra-t-elle se connecter à d'autres logiciels utilisés par le département (gestion administrative, paie, logiciel métier déjà en place) ?: Pour l'instant non Les agents du département ont-ils déjà un compte informatique professionnel (Active Directory, messagerie @departement.fr) qu'ils utilisent pour accéder à leurs outils ?: Non, chaque outil a ses propres identifiants Dans 12 mois, si la plateforme fonctionne parfaitement, qu'est-ce qui aura vraiment changé dans votre quotidien ?: Nous aurons gagné du temps et les travailleurs sociaux du département pourront avoir plus de temps pour les enfants et le contrôle des établissements d'accueil
✓ Les utilisateurs, les rôles et les règles métier

[Les utilisateurs, les rôles et les règles métier] Quels sont les différents types de personnes qui utiliseront la plateforme et quel est leur rôle principal ?: Un premier lieu, les travailleurs sociaux du département, pour faire les offres de placements auprès des établissements et faire le suivi des demandes. Ensuite pouvoir géréer le dossier de l'enfant, saisir des infos, uploader des documents. Les lieux d'accueils également: pour recevoir les demandes et compléter le dossier de l'enfant en fonction des actions prises, des compte d'activité, la scolarité et le professionnel, et également pouvoir signaler s'ils ont des places indiponibles Qu'est-ce qu'une 'place disponible' pour vous ? Est-ce que cela dépend du profil de l'enfant (age, genre, besoin spécifique) ?: Oui une place disponible est définis par des critères de l'enfant et la corrélation avec les caracteristiques de l'établissement. Par example un enfant de 12 garçon, ne peut pas être placé dans un établissement n'accueillant que des filles Comment doit fonctionner la transmission d'un rapport d'établissement vers le conseiller ? Y a-t-il une validation, une signature, une périodicité obligatoire ?: Les transmissions de rapport sont juste des comptes saisies par l'établissement ou le conseiller. Si c'est par l'établissement alors le conseiller en charge du suivi de l'enfant doit recevoir une notification Quand vous parlez de 'faciliter la communication entre professionnels', quelle forme cela doit-il prendre concrètement ?: Messagerie interne privée entre professionnels autour d'un enfant, Notifications et alertes automatiques (place libérée, rapport déposé, échéance...), Un fil de discussion attaché au dossier de l'enfant, Partage de documents entre professionnels, Agenda partagé / planning des échéances Quels types de documents devrez-vous générer depuis la plateforme ?: Tous les documents qui touchent à l'enfant: judiciaires, médical, dossier info comme pièce d'identité etc... L'enfant lui-même ou sa famille aura-t-il accès à une partie de la plateforme (consultation du dossier, droit d'accès RGPD) ?: Non, la plateforme est réservée aux professionnels

[Priorités, périmètre et contraintes] Parmi toutes les fonctionnalités décrites, lesquelles sont absolument indispensables dès le départ pour que la plateforme soit utile ?: Tableau de bord des places disponibles en temps réel, Dossier complet de l'enfant (informations, documents, historique), Demandes de placement avec matching profil/établissement, Suivi scolaire et professionnel de l'enfant, Saisie de rapports et comptes-rendus par les établissements, Notifications automatiques, Gestion des rôles et des droits d'accès, Historique et traçabilité RGPD anonymisable, Messagerie et fil de discussion autour du dossier enfant Quand un travailleur social cherche une place : envoie-t-il une demande à un seul établissement à la fois, ou à plusieurs simultanément ?: Plusieurs établissements en même temps Qui sera responsable de gérer les comptes utilisateurs et les droits d'accès sur la plateforme (créer un compte, donner ou retirer des accès) ?: Un administrateur désigné côté département Avez-vous une enveloppe budgétaire définie pour ce projet ?: Pas encore défini Y a-t-il une échéance particulière à respecter pour le lancement (décision politique, appel d'offre, début d'année scolaire...) ?: Septembre 2026 Avez-vous envisagé d'utiliser l'intelligence artificielle dans la plateforme (suggestions automatiques de placement, analyse de dossiers, alertes prédictives...) ?: Oui, à envisager dans une version future
✓ Impact et mesure du succès


[Impact et mesure du succès] Comment saurez-vous que la plateforme est un succès ? Y a-t-il des résultats concrets que vous pourrez mesurer (temps gagné, nombre d'appels évités, délais de placement réduits...) ?: temps gagné, nombre d'appels évités, délais de placement réduits. Avez-vous des inquiétudes sur l'adoption de la plateforme par les établissements ou les familles d'accueil (certains pourraient résister au changement ou avoir des difficultés avec le numérique) ?: Oui, le premier lieu d'inquiétude est déjà l'adoption par les départements eux-même.

[Solinn — Impact et mise en œuvre]
Aujourd'hui, combien de temps prend en moyenne la recherche d'une place disponible pour un enfant (du premier appel à la confirmation) ?: 1 à 3 jours
Combien de nouvelles demandes de placement sont traitées en moyenne par mois dans un département ?: Moins de 20
Avez-vous déjà un plan pour accompagner les établissements dans la prise en main ? (formation, référent numérique, support…): non
Le département pilote est-il déjà identifié ? Si oui, avez-vous une idée de ses contraintes particulières ?: Oui l'Ain
Les données Excel à importer concernent quoi principalement ?: Liste des établissements et leurs capacités, Historique des placements passés, Listes d'utilisateurs / travailleurs sociaux

[Solinn — Impact organisationnel et mise en production]
Y a-t-il une personne côté département de l'Ain qui sera le référent interne de la plateforme (un 'champion' qui fera adhérer les collègues) ?: Non, ce n'est pas encore défini
Comment envisagez-vous la formation des travailleurs sociaux et des établissements à la prise en main ? (optionnel): Formation présentielle organisée par Solinn
Comment souhaitez-vous déployer la plateforme au département de l'Ain : tout d'un coup ou progressivement ?: Déploiement complet en une seule fois
Les professionnels auront-ils besoin d'utiliser la plateforme depuis un téléphone ou une tablette (notamment les familles d'accueil ou les éducateurs en déplacement) ?: Oui, ce serait un plus mais pas obligatoire
Le département de l'Ain dispose-t-il d'un Délégué à la Protection des Données (DPO) avec qui coordonner la conformité RGPD de la plateforme ?: Oui, mais son implication reste à définir
Après l'Ain, avez-vous une vision du rythme d'ouverture à d'autres départements ? (optionnel): Quelques départements supplémentaires dans les 12 mois suivants

HDS: OVH pour les fichiers - gérer par un cabinet avocat pour la compliance.
Critère de filtre pour admission lieux d'accueil: age (0-3, 3-6, 6-9, 9-12, 12-18), genre et handicap
`